datomic:
    build: .
    net: "host"
    volumes:
        - /home/vagrant:/home/developer
        - /home/vagrant:/pwd
    environment:
        AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    user: 1000:1000
    stdin_open: true
    tty: true
    entrypoint: /opt/datomic-pro-0.9.5350/bin/datomic
    command: describe-license
